#!/bin/bash

function systemd_update_metadata_info()
{
    systemctl start lastore-update-metadata-info.service
}

function update_metadata_info_now()
{
    /usr/bin/lastore-tools update -r desktop -j applications -o /var/lib/lastore/applications.json
    /usr/bin/lastore-tools update -r desktop -j categories -o /var/lib/lastore/categories.json
    /usr/bin/lastore-tools update -r desktop -j xcategories -o /var/lib/lastore/xcategories.json
    /usr/bin/lastore-tools update -r desktop -j mirrors -o /var/lib/lastore/mirrors.json
}

case "$1" in
    "-now")
        update_metadata_info_now
        ;;
    *)
        if [[ -S /var/run/systemd/notify ]]; then
            systemd_update_metadata_info
        else
            update_metadata_info_now
        fi
        ;;
esac



