.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2010-2021, Deepin Technology Co., Ltd.
.\"
.TH "LASTORE-TOOLS "1" "2021-03-29" "lastore-tools manpage"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lastore-tools \- New Deepin tool to help building dstore system.

.SH DESCRIPTION
.PP
.B lastore-tools
is a new Deepin tool to help building dstore system.
.SH OPTIONS
.PP
-update   Update appstore information from server
.PP
-test   Run test job using lastore-daemon
.PP
-help, h	Shows a list of commands or help for one command
.SH AUTHOR
.PP
.B lastore-tools
is maintain by Song Wentai
.PP
This manual page was written by
.MT lichangze@\:uniontech.com
Li Changze
