// Code generated by "dbusutil-gen em -type SmartMirror"; DO NOT EDIT.

package main

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *SmartMirror) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "Query",
			Fn:      v.Query,
			InArgs:  []string{"original", "officialMirror", "mirrorHost"},
			OutArgs: []string{"url"},
		},
		{
			Name:   "SetEnable",
			Fn:     v.SetEnable,
			InArgs: []string{"enable"},
		},
	}
}
