######################################################################
# Automatically generated by qmake (3.0) Mon Jul 20 01:05:44 2015
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../../../../include/

QT += dbus

#CONFIG += C++11

# Input
HEADERS += ../../../../include/lastore-daemon.h
SOURCES += main.cpp test_lastore.cpp
